# Generated by Django 3.2.5 on 2021-07-26 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('data', models.DateField()),
                ('inicio', models.CharField(max_length=5)),
                ('final', models.CharField(max_length=5)),
                ('endereco', models.CharField(max_length=155)),
                ('endereco2', models.CharField(blank=True, max_length=155, null=True)),
                ('cep', models.CharField(max_length=50)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
