# Generated by Django 3.2.5 on 2021-07-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('inicio', models.CharField(max_length=5)),
                ('final', models.CharField(max_length=5)),
                ('foto', models.ImageField(upload_to='artistas/img/')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventos.evento')),
            ],
        ),
    ]
